hdi <- read.table("C:/Users/jderiggi/Documents/ndi_un/multiDi.csv",row.names=1, header=TRUE, sep=',')
hdi <- na.omit(hdi)
hdi <- scale(hdi)
d <- dist(hdi, method='euclidean')
fit <-hclust(d, method='ward.D')
svg(filename="C:/Users/jderiggi/Documents/ndi_un/dendrogram_2.svg", height=40, width=60)
plot(fit)
dev.off()
